jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"

# Nécessaire pour adopter des politiques d'exclusion sur les champs des entités étendues (type FOSUserBundle etc.)
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: '%kernel.project_dir%/config/serializer/FOSUserBundle'
