lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'

    token_ttl:        86400                                   # token ttl - defaults to 86400

    # token extraction settings
    token_extractors:
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer
