lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/default_private.pem'
    public_key: '%kernel.project_dir%/config/jwt/default_public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_ttl:        86400                                   # token ttl - defaults to 86400

    # token extraction settings
    token_extractors:
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer
