#nelmio_api_doc:
#    exclude_sections:     []
#    default_sections_opened:  true
#    motd:
#        template:             'NelmioApiDocBundle::Components/motd.html.twig'
#    request_listener:
#        enabled:              true
#        parameter:            _doc
#    swagger:
#        api_base_path:        /api
#        swagger_version:      '1.2'
#        api_version:          '0.1'
#        info:
#            title:                Symfony2
#            description:          'My awesome Symfony2 app!'
#            TermsOfServiceUrl:    null
#            contact:              null
#            license:              null
#            licenseUrl:           null
#    cache:
#        enabled:              false
#        file:                 '%kernel.cache_dir%/api-doc.cache'

nelmio_api_doc:
    name: uPont API
    sandbox:
        authentication:
            name: Authorization
            delivery: header
            type:     bearer
        accept_type: application/json
        body_format:
            formats: [ ]
            default_format: json
        request_format:
            formats:
                json: application/json
            method: accept_header
            default_format: json
