security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MODO:       [ROLE_USER, ROLE_JARDINIER]
        ROLE_ADMIN:      [ROLE_MODO, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # Procédure de login

        ping:
            methods: [GET, HEAD]
            pattern: ^/ping
            security: false

        config:
            methods: [GET]
            pattern: ^/config
            security: false

        resetting:
            methods: [POST]
            pattern: ^/resetting
            security: false

        download:
            methods: [GET]
            pattern: ^/courses/.+/exercices/.+/download
            security: false

        calendar:
            methods: [GET]
            pattern: ^/users/.+/calendar
            security: false

        dev:
            pattern: ^/(_(profiler|wdt|doc)|css|images|js)/
            security: false

        # Firewall principal
        api:
            pattern:   ^/.+
            stateless: true
            anonymous: true
            provider: fos_userbundle
            simple_preauth:
              authenticator: App\Security\SSOKIAccessTokenAuthenticator
#            guard:
#              authenticators:
#                - App\Security\SSOKIAccessTokenAuthenticator

    access_control:
        - { path: ^/(clubs)(/[a-zA-Z]+)?,             methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,                            methods: [GET, POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ping,                             methods: [HEAD, GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/config,                           methods: [GET], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/courses,                          methods: [HEAD], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coffee,                           methods: [GET],  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/version,                          methods: [GET],  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/filelist,                         methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users,                            methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^, roles: IS_AUTHENTICATED_FULLY }
