services:
    # Écoute les checks d'achievements demandés un peu partout dans le code
    ki_user.listener.achievementcheck:
        class: KI\UserBundle\Listener\AchievementCheckListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: kernel.event_listener, event: upont.achievement, method: check }

    ki_user.listener.jwt_created:
        class: KI\UserBundle\Listener\JWTCreatedListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    ki_user.listener.jwt_decoded:
        class: KI\UserBundle\Listener\JWTDecodedListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    # Écoute le lancement de notifications push
    ki_user.listener.notification:
        class: KI\UserBundle\Listener\NotificationListener
        arguments:
            - '@ki_core.service.curl'
            - '%ki_upont.push.gcm%'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    # Ajoute les gens online
    ki_user.listener.online:
        class: KI\UserBundle\Listener\OnlineListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ki_user.listener.user_registration.send_mail:
        class: KI\UserBundle\Listener\SendMailUserRegistrationListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: upont.user_registration, method: sendMail }

    ki_user.listener.user_registration.facebook_import:
        class: KI\UserBundle\Listener\FacebookImportUserRegistrationListener
        arguments:
            - '@ki_core.service.curl'
            - '@ki_core.service.image'
            - '@doctrine.orm.entity_manager'
            - '%facebook_token%'
        tags:
            - { name: kernel.event_listener, event: upont.user_registration, method: facebookImport }
