services:
    ki_user.repository.admissible:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\Admissible

    ki_user.repository.clubuser:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\ClubUser

    ki_user.repository.device:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\Device

    ki_user.repository.facegame:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\Facegame

    ki_user.repository.notification:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\Notification

    ki_user.repository.user:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\UserBundle\Entity\User
