clubs:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\ClubsController

users:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\UsersController

own:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\OwnController

promo:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\PromoController

groups:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\GroupsController

experiences:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\ExperiencesController

admissibles:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\AdmissiblesController

facegames:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\FacegamesController

upont_api_own_calendar:
    pattern: /users/{token}/calendar
    defaults: { _controller: KI\UpontBundle\Controller\Users\OwnController::getOwnCalendarAction }
    requirements:
        _method: GET

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
