clubs:
    type:     rest
    resource: KI\UserBundle\Controller\ClubsController

users:
    type:     rest
    resource: KI\UserBundle\Controller\UsersController

own:
    type:     rest
    resource: KI\UserBundle\Controller\OwnController

promo:
    type:     rest
    resource: KI\UserBundle\Controller\PromoController

groups:
    type:     rest
    resource: KI\UserBundle\Controller\GroupsController

experiences:
    type:     rest
    resource: KI\UserBundle\Controller\ExperiencesController

admissibles:
    type:     rest
    resource: KI\UserBundle\Controller\AdmissiblesController

default:
    type:     rest
    resource: KI\UserBundle\Controller\DefaultController

facegames:
    type:     rest
    resource: KI\UserBundle\Controller\FacegamesController

upont_api_own_calendar:
    pattern: /users/{token}/calendar
    defaults: { _controller: KI\UserBundle\Controller\OwnController::getOwnCalendarAction }
    requirements:
        _method: GET

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
