clubs:
    type:     rest
    resource: KI\UserBundle\Controller\ClubsController

pontlyvalents:
    type:     rest
    resource: KI\UserBundle\Controller\PontlyvalentsController

users:
    type:     rest
    resource: KI\UserBundle\Controller\UsersController

own:
    type:     rest
    resource: KI\UserBundle\Controller\OwnController

promo:
    type:     rest
    resource: KI\UserBundle\Controller\PromoController

groups:
    type:     rest
    resource: KI\UserBundle\Controller\GroupsController

admissibles:
    type:     rest
    resource: KI\UserBundle\Controller\AdmissiblesController

default:
    type:     rest
    resource: KI\UserBundle\Controller\DefaultController

facegames:
    type:     rest
    resource: KI\UserBundle\Controller\FacegamesController

upont_api_own_calendar:
    path: /users/{token}/calendar
    defaults: { _controller: KI\UserBundle\Controller\OwnController::getOwnCalendarAction }
    methods: [GET]

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting
