parameters:
    # Notifications push
    ki_upont.push.gcm: 'AIzaSyCHrIJMqsou89Er6ksjfuqIZQLdOsuky2Q'

services:
    # Permet de gérer des tokens comme on veut
    ki_user.service.token:
        class: KI\UserBundle\Service\TokenService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    # Gère l'envoi de mails
    ki_user.service.mailer:
        class: KI\UserBundle\Service\MailerService
        arguments:
            - '@mailer'
            - '@templating'

    # Gère l'envoi de notification
    ki_user.service.notify:
        class: KI\UserBundle\Service\NotifyService
        arguments:
            - '@ki_user.service.gcm'
            - '@doctrine.orm.entity_manager'
            - '@ki_user.repository.device'
            - '@ki_user.repository.user'

    # Interface Google Cloud Messages
    ki_user.service.gcm:
        class: KI\UserBundle\Service\GcmService
        arguments:
            - '@ki_core.service.curl'
            - %ki_upont.push.gcm%

    # Interface avancée de gestion des permissions utilisateurs
    ki_user.service.permission:
        class: KI\UserBundle\Service\PermissionService
        arguments:
            - '@ki_user.repository.clubuser'

    form_login_authenticator:
        class: KI\UserBundle\Security\FormLoginAuthenticator
        arguments:
          - '@security.password_encoder'
          - '@lexik_jwt_authentication.jwt_manager'
          - '@event_dispatcher'
        public: false

    jwt_authenticator:
        class: KI\UserBundle\Security\JwtAuthenticator
        autowire: true
