services:
    # Écoute le lancement de notifications push
    ki_upont.listener.notification:
        class: KI\UpontBundle\EventListener\NotificationListener
        arguments:
            container: "@service_container"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    # Écoute les checks d'achievements demandés un peu partout dans le code
    ki_upont.listener.achievement:
        class: KI\UpontBundle\EventListener\AchievementListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: upont.achievement, method: check }

    ki_upont.type.club_selector:
       class: KI\UpontBundle\Form\Type\ClubSelectorType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
           - { name: form.type, alias: club_selector }
    # Interface cURL
    ki_upont.token:
        class: KI\UpontBundle\Services\KIToken
        calls:
            - [ setContainer,[ @service_container ] ]
    # Sert pour la compatibilité FOSUserBundle
    ki_upont.registration.form.type:
        class: KI\UpontBundle\Form\Users\UserType
        tags:
            - { name: form.type, alias: user }

    # Ajoute les gens online
    ki_upont.online:
        class: KI\UpontBundle\EventListener\OnlineListener
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    # Permet de gérer le JSON Web Token
    upont_api.event.jwt_response_listener:
        class: %upont_api.event.jwt_response_listener.class%
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    upont_api.event.jwt_created_listener:
        class: %upont_api.event.jwt_created_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    upont_api.event.jwt_decoded_listener:
        class: %upont_api.event.jwt_decoded_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
parameters:
    # Tokens
    upont_api.event.jwt_response_listener.class: KI\UpontBundle\EventListener\JWTResponseListener
    upont_api.event.jwt_created_listener.class: KI\UpontBundle\EventListener\JWTCreatedListener
    upont_api.event.jwt_decoded_listener.class: KI\UpontBundle\EventListener\JWTDecodedListener

    # Notifications push
    upont_push_GCM_API_key: 'AIzaSyCHrIJMqsou89Er6ksjfuqIZQLdOsuky2Q'
    upont_push_WP_url: ''
