services:
    # Auto set l'utilisateur pour les entités en faisant le choix
    ki_user.setter.user:
        class: KI\UserBundle\Setter\UserSetter
        arguments:
            - @security.token_storage
        tags:
            - { name: doctrine.event_listener, event: prePersist }
