filter:
    paths: [back/*]
    excluded_paths: [back/vendor/*, back/app/*, back/src/KI/UpontBundle/DataFixtures/*, back/src/KI/UpontBundle/Controller/MigrationController.php]
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: true
        side_effects_or_types: true
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: true
        no_global_keyword: true
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: false
        avoid_superglobals: true
        security_vulnerabilities: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        fix_doc_comments: false

coding_style:
    php:
        indentation:
            switch:
                indent_case: false
        spaces:
            around_operators:
                multiplicative: false
            other:
                after_type_cast: false
        braces:
            if:
                always: false
tools:
    external_code_coverage:
        timeout: 1200
        runs: 8
