version: "3"

services:
    db:
        image: mysql
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        restart: always

    upont-front:
        image: kiclubinfo/upont/front
        build:
            context: front
        restart: always

    # pochtron2:
    #     image: kiclubinfo/pochtron2
    #     restart: always

    upont-back:
        image: kiclubinfo/upont/back
        build:
            context: back
        environment:
            - SYMFONY_ENV
        volumes:
            # Strange but correct
            - ./docker/config/jwt:/app/app/var/jwt:ro
            - upont-uploads:/app/web/uploads:rw
        links:
            - db
        environment:
            - MYSQL_HOST=db
        env_file:
            - .env
        restart: always

    ingress:
        image: kiclubinfo/upont/ingress
        build:
            context: docker/ingress
        volumes:
            - ./docker/upont-docker-preprod.enpc.fr.conf:/etc/nginx/sites-enabled/upont.conf:ro
        links:
            - upont-back
            - upont-front
            # - pochtron2
        ports:
            - 8080:80
        restart: always

volumes:
    db-data:
        driver: local
    upont-uploads:
        driver: local
