version: "2.3"

services:
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        restart: always

    upont-front:
        image: quay.io/kiclubinfo/upont-front:${TAG:-latest}
        build:
            context: front
        restart: always

    # pochtron2:
    #     image: kiclubinfo/pochtron2
    #     restart: always

    upont-back:
        image: quay.io/kiclubinfo/upont-back:${TAG:-latest}
        build:
            context: back
        volumes:
            - ./docker/config/jwt:/app/config/jwt:ro
            - upont-uploads:/app/public/uploads:rw
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
        env_file:
            - .env
        restart: always

    ingress:
        image: quay.io/kiclubinfo/upont-ingress:${TAG:-latest}
        build:
            context: docker/ingress
        volumes:
            - ./docker/upont-docker-preprod.enpc.fr.conf:/etc/nginx/sites-enabled/upont.conf:ro
        depends_on:
            - upont-back
            - upont-front
            # - pochtron2
        ports:
            - 8080:80
        restart: always

volumes:
    db-data:
        driver: local
    upont-uploads:
        driver: local
