version: "2.3"

services:
  db:
    image: mysql:5.7
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=${DATABASE_NAME}
    - MYSQL_USER=${DATABASE_USER}
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    restart: always

  db-backup:
    image: selim13/automysqlbackup
    volumes:
      - "./docker/db-backup:/backup"
    environment:
      USERNAME: ${DATABASE_USER}
      PASSWORD: ${DATABASE_PASSWORD}
      DBHOST: db
      CRON_SCHEDULE: "0 0 * * *"
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    environment:
    - PMA_HOST=db
    ports:
    - 127.0.0.1:10102:80
    restart: always

  upont-front:
    image: quay.io/kiclubinfo/upont-front:${TAG:-latest}
    restart: always

  upont-back:
    image: quay.io/kiclubinfo/upont-back:${TAG:-latest}
    volumes:
    - "./docker/upont-back/jwt:/app/config/jwt:ro"
    - upont-uploads:/app/public/uploads:rw
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    env_file:
    - .env
    restart: always

  ingress:
    image: quay.io/kiclubinfo/upont-ingress:${TAG:-latest}
    volumes:
    - upont-uploads:/upont/uploads:ro
    depends_on:
    - upont-back
    - upont-front
    ports:
    - 127.0.0.1:10101:80
    restart: always

volumes:
  db-data:
    driver: local
  upont-uploads:
    driver: local
