version: "2.3"

services:
  db:
    image: mysql:5.7
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=${DATABASE_NAME}
    - MYSQL_USER=${DATABASE_USER}
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    restart: always

  upont-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    environment:
    - PMA_HOST=db
    networks:
    - public
    restart: always

  upont-front:
    image: quay.io/kiclubinfo/upont-front:${TAG:-latest}
    restart: always

  upont-back:
    image: quay.io/kiclubinfo/upont-back:${TAG:-latest}
    volumes:
    - ./docker/config/jwt:/app/config/jwt:ro
    - upont-uploads:/app/public/uploads:rw
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    env_file:
    - .env
    restart: always

  ingress:
    image: quay.io/kiclubinfo/upont-ingress:${TAG:-latest}
    volumes:
    - upont-uploads:/upont/uploads:ro
    depends_on:
    - upont-back
    - upont-front
    networks:
    - public
    restart: always

volumes:
  db-data:
    driver: local
  upont-uploads:
    driver: local

networks:
  public:
    external: true
