version: "2.3"

services:
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        environment:
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - 8081:80
        restart: always

volumes:
    db-data:
