version: "2.3"

services:
    upont-front:
        image: quay.io/kiclubinfo/upont-front:${TAG:-latest}
        restart: always

    upont-back:
        image: quay.io/kiclubinfo/upont-back:${TAG:-latest}
        volumes:
            - ./docker/config/jwt:/app/config/jwt:ro
            - upont-uploads:/app/public/uploads:rw
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
        env_file:
            - .env
        restart: always

    ingress:
        image: quay.io/kiclubinfo/upont-ingress:${TAG:-latest}
        volumes:
            - ./docker/upont-docker-preprod.enpc.fr.conf:/etc/nginx/sites-enabled/upont.conf:ro
        depends_on:
            - upont-back
            - upont-front
        ports:
            - 8080:80
        restart: always

volumes:
    upont-uploads:
