services:
    ki_foyer.helper.beer:
        class: KI\FoyerBundle\Helper\BeerHelper
        arguments:
            - @ki_foyer.repository.beer
            - @ki_foyer.repository.beeruser
            - @ki_user.repository.user
            - @event_dispatcher

    ki_foyer.helper.statistics:
        class: KI\FoyerBundle\Helper\FoyerStatisticsHelper
        arguments:
            - @ki_foyer.repository.beer
            - @ki_foyer.repository.beeruser
            - @ki_user.repository.user
