services:
    ki_foyer.helper.beer:
        class: KI\FoyerBundle\Helper\BeerHelper
        arguments:
            - '@ki_foyer.repository.beer'
            - '@ki_foyer.repository.transaction'
            - '@KI\UserBundle\Repository\UserRepository'
            - '@event_dispatcher'

    ki_foyer.helper.transaction:
        class: KI\FoyerBundle\Helper\TransactionHelper
        arguments:
            - '@ki_foyer.repository.beer'
            - '@ki_foyer.repository.transaction'
            - '@KI\UserBundle\Repository\UserRepository'
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
