services:
    ki_foyer.repository.beer:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\FoyerBundle\Entity\Beer

    ki_foyer.repository.transaction:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\FoyerBundle\Entity\Transaction
