beers:
    type:     rest
    resource: KI\FoyerBundle\Controller\BeersController

transactions:
    type:     rest
    resource: KI\FoyerBundle\Controller\TransactionsController

default:
    type:     rest
    resource: KI\FoyerBundle\Controller\DefaultController

youtubes:
    type:     rest
    resource: KI\FoyerBundle\Controller\YoutubesController
