beers:
    type:     rest
    resource: KI\FoyerBundle\Controller\BeersController

beerUsers:
    type:     rest
    resource: KI\FoyerBundle\Controller\BeerUsersController

default:
    type:     rest
    resource: KI\FoyerBundle\Controller\DefaultController

youtubes:
    type:     rest
    resource: KI\FoyerBundle\Controller\YoutubesController
