services:
    # Communique avec l'API du Foyer
    ki_foyer.service.foyer:
        class: KI\FoyerBundle\Service\FoyerService
        arguments:
            - '@ki_core.service.curl'
            - '@event_dispatcher'
            - '@security.context'
