services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KI\FoyerBundle\:
        resource: '../../*'
        exclude: '../../{Entity,DataFixtures}'

    KI\FoyerBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    KI\FoyerBundle\Listener\SendMailNegativeBalanceListener:
        tags:
            - { name: kernel.event_listener, event: upont.negative_balance, method: sendMail }
