upont_api_ponthub_filelist:
    pattern: /filelist
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::filelistAction }
    requirements:
        _method: POST

upont_api_ponthub_gracenote:
    pattern: /gracenote
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::gracenoteAction }
    requirements:
        _method: POST

upont_api_ponthub_imdb_search:
    pattern: /imdb/search
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::imdbSearchAction }
    requirements:
        _method: POST

upont_api_ponthub_imdb_infos:
    pattern: /imdb/infos
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::imdbInfosAction }
    requirements:
        _method: POST

upont_api_ponthub_search:
    pattern: /search
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::searchAction }
    requirements:
        _method: POST

upont_api_ponthub_statistics:
    pattern: /statistics
    defaults: { _controller: KI\UpontBundle\Controller\Ponthub\PonthubController::statisticsAction }
    requirements:
        _method: GET


# Ressources REST

albums:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\AlbumsController

games:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\GamesController

movies:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\MoviesController

others:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\OthersController

softwares:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\SoftwaresController

requests:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\RequestsController

series:
    type:     rest
    resource: KI\UpontBundle\Controller\Ponthub\SeriesController
