# Routes du système de likes/dislikes/commentaires, applicables à beaucoup d'objets


upont_api_ponthub_likes_post_dislike:
    pattern: /{object}/{slug}/dislike
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::dislikeAction }
    requirements:
        _method: POST
        
upont_api_ponthub_likes_delete_like:
    pattern: /{object}/{slug}/like
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::deleteLikeAction }
    requirements:
        _method: DELETE

upont_api_ponthub_likes_delete_dislike:
    pattern: /{object}/{slug}/dislike
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::deleteDislikeAction }
    requirements:
        _method: DELETE

upont_api_ponthub_likes_get_comments:
    pattern: /{object}/{slug}/comments
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::getCommentsAction }
    requirements:
        _method: GET

upont_api_ponthub_likes_post_comments:
    pattern: /{object}/{slug}/comments
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::postCommentAction }
    requirements:
        _method: POST

upont_api_ponthub_likes_patch_comments:
    pattern: /{object}/{slug}/comments/{id}
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::patchCommentAction }
    requirements:
        _method: PATCH
               
upont_api_ponthub_likes_delete_comments:
    pattern: /{object}/{slug}/comments/{id}
    defaults: { _controller: KI\UpontBundle\Controller\Core\LikeableController::deleteCommentAction }
    requirements:
        _method: DELETE
