events:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\EventsController

newsitems:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\NewsitemsController

courses:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\CoursesController

exercices:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\ExercicesController

fixes:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\FixesController

tutos:
    type:     rest
    resource: KI\UpontBundle\Controller\Publications\TutosController
