clubs:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\ClubsController

users:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\UsersController

own:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\OwnController

promo:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\PromoController
    
experiences:
    type:     rest
    resource: KI\UpontBundle\Controller\Users\ExperiencesController

upont_api_own_calendar:
    pattern: /users/{token}/calendar
    defaults: { _controller: KI\UpontBundle\Controller\Users\OwnController::getOwnCalendarAction }
    requirements:
        _method: GET
