parameters:
  upont:
    foyer:
      trust:
        - '017'

    promos:
      latest: '019'
      assos: '017'
      all:
        - '014'
        - '015'
        - '016'
        - '017'
        - '018'
        - '019'

    pontlyvalent:
      open: true
      promo: '017'

services:
  # If you need to access services in a test, create an alias
  # and then fetch that alias from the container. As a convention,
  # aliases are prefixed with test. For example:

  test.App\Service\CurlService:
    alias: '@App\Service\CurlService'
    public: true

  test.App\Service\ImageService:
    alias: '@App\Service\ImageService'
    public: true
