services:
    # Envoie un message Slack quand il y a un feedback
    ki_clubinfo.listener.fix:
        class: KI\ClubinfoBundle\Listener\FixListener
        arguments:
            - @ki_clubinfo.service.slack
            - @event_dispatcher
        tags:
            - { name: doctrine.event_listener, event: postPersist }
