fixs:
    type:     rest
    resource: KI\ClubinfoBundle\Controller\FixsController

tutos:
    type:     rest
    resource: KI\ClubinfoBundle\Controller\TutosController

centrales:
    type:     rest
    resource: KI\ClubinfoBundle\Controller\CentralesController
