services:
    ki_publication.repository.course:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - KI\PublicationBundle\Entity\Course

    ki_publication.repository.courseuser:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - KI\PublicationBundle\Entity\CourseUser
