events:
    type:     rest
    resource: KI\PublicationBundle\Controller\EventsController

newsitems:
    type:     rest
    resource: KI\PublicationBundle\Controller\NewsitemsController

messages:
    type:     rest
    resource: KI\PublicationBundle\Controller\MessagesController

courses:
    type:     rest
    resource: KI\PublicationBundle\Controller\CoursesController

exercices:
    type:     rest
    resource: KI\PublicationBundle\Controller\ExercicesController
