events:
    type:     rest
    resource: KI\PublicationBundle\Controller\EventsController

newsitems:
    type:     rest
    resource: KI\PublicationBundle\Controller\NewsitemsController

newsitem_files:
    type:     rest
    resource: KI\PublicationBundle\Controller\NewsitemFilesController

messages:
    type:     rest
    resource: KI\PublicationBundle\Controller\MessagesController

courses:
    type:     rest
    resource: KI\PublicationBundle\Controller\CoursesController

exercices:
    type:     rest
    resource: KI\PublicationBundle\Controller\ExercicesController
