services:
    # Permet de générer un calendrier ICS pour un utilisateur donné
    KI\PublicationBundle\Service\CalendarService:
        arguments:
            - '@bomo_ical.ics_provider'
            - '@event_dispatcher'
