parameters:
    # Tokens d'accès API Gracenote
    ki_ponthub.files.valid_extensions: ['mp3', 'wav', 'ogg', 'flac', 'mp2', 'aac', 'avi', 'mpeg', 'mp4', 'mkv', 'rar', 'zip', 'iso', 'exe', 'msi', 'jpg', 'jpeg', 'png', 'bmp', 'gif', 'srt', 'pdf', 'epub', 'mobi']

services:
    ki_ponthub.helper.filelist:
        class: KI\PonthubBundle\Helper\FilelistHelper
        arguments:
            - @doctrine.orm.entity_manager
            - @ki_ponthub.repository.album
            - @ki_ponthub.repository.genre
            - @ki_ponthub.repository.serie
            - @ki_ponthub.repository.ponthubfile
            - %ki_ponthub.files.valid_extensions%
            - @ki_ponthub.helper.file

    ki_ponthub.helper.file:
        class: KI\PonthubBundle\Helper\FileHelper
        arguments:
            - @doctrine.orm.entity_manager

    ki_ponthub.helper.global_statistics:
        class: KI\PonthubBundle\Helper\GlobalStatisticsHelper
        arguments:
            - @doctrine.orm.entity_manager
            - @ki_ponthub.repository.ponthubfile
            - @ki_ponthub.repository.ponthubfileuser

    ki_ponthub.helper.statistics:
        class: KI\PonthubBundle\Helper\StatisticsHelper
        arguments:
            - @ki_ponthub.repository.ponthubfileuser
