services:
    ki_ponthub.listener.ponthubfile:
        class: KI\PonthubBundle\Listener\PonthubFileListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    ki_ponthub.listener.ponthubfileuser:
        class: KI\PonthubBundle\Listener\PonthubFileUserListener
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ki_ponthub.listener.serie:
        class: KI\PonthubBundle\Listener\SerieListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }
