services:
    ki_ponthub.repository.actor:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\PonthubBundle\Entity\Actor

    ki_ponthub.repository.genre:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\PonthubBundle\Entity\Genre

    ki_ponthub.repository.ponthubfile:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\PonthubBundle\Entity\PonthubFile

    ki_ponthub.repository.ponthubfileuser:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\PonthubBundle\Entity\PonthubFileUser

    ki_ponthub.repository.serie:
        class: KI\PonthubBundle\Repository\SerieRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\PonthubBundle\Entity\Serie
