services:
    ki_ponthub.selector.actors:
       class: KI\PonthubBundle\Selector\ActorsSelector
       arguments:
           - '@ki_ponthub.transformer.actors'
       tags:
           - { name: form.type, alias: actors_selector }

    ki_ponthub.selector.genres:
       class: KI\PonthubBundle\Selector\GenresSelector
       arguments:
           - '@ki_ponthub.transformer.genres'
       tags:
           - { name: form.type, alias: genres_selector }
