services:
    ki_ponthub.selector.actors:
       class: KI\PonthubBundle\Selector\ActorsSelector
       arguments:
           - @doctrine.orm.entity_manager
       tags:
           - { name: form.type, alias: actors_selector }

    ki_ponthub.selector.genres:
       class: KI\PonthubBundle\Selector\GenresSelector
       arguments:
           - @doctrine.orm.entity_manager
       tags:
           - { name: form.type, alias: genres_selector }

    # Communique avec l'API Gracenote
    ki_ponthub.service.gracenote:
        class: KI\PonthubBundle\Service\GracenoteService

    # Communique avec l'API Imdb
    ki_ponthub.service.imdb:
        class: KI\PonthubBundle\Services\ImdbService

parameters:
    # Tokens d'accès API Gracenote
    ki_ponthub.gracenote.key1: '14886144'
    ki_ponthub.gracenote.key2: '136467B84B6BCA2854F072597B216096'
    ki_ponthub.gracenote.key3: '280723858430018941-61BBB34090F9F4CD6C5D5F903990135F'
