services:
    ki_upont.type.actors_selector:
       class: KI\UpontBundle\Form\Type\ActorsSelectorType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
           - { name: form.type, alias: actors_selector }
    ki_upont.type.genres_selector:
       class: KI\UpontBundle\Form\Type\GenresSelectorType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
           - { name: form.type, alias: genres_selector }

    # Communique avec l'API Gracenote
    ki_upont.gracenote:
        class: KI\UpontBundle\Services\KIGracenote
        calls:
            - [ setContainer,[ @service_container ] ]

    # Communique avec l'API Imdb
    ki_upont.imdb:
        class: KI\UpontBundle\Services\KIImdb
        calls:
            - [ setContainer,[ @service_container ] ]
parameters:
    # API Gracenote
    upont_gracenote_key1: '14886144' # Tokens d'accès API Gracenote
    upont_gracenote_key2: '136467B84B6BCA2854F072597B216096'
    upont_gracenote_key3: '280723858430018941-61BBB34090F9F4CD6C5D5F903990135F'
