parameters:
    # Tokens d'accès API Gracenote
    ki_ponthub.gracenote.key1: '14886144'
    ki_ponthub.gracenote.key2: '136467B84B6BCA2854F072597B216096'
    ki_ponthub.gracenote.key3: '279881507270543439-482465B59397C267B124C2794482BF35'

services:
    # Communique avec l'API Gracenote
    ki_ponthub.service.gracenote:
        class: KI\PonthubBundle\Service\GracenoteService
        arguments:
            - '%ki_ponthub.gracenote.key1%'
            - '%ki_ponthub.gracenote.key2%'
            - '%ki_ponthub.gracenote.key3%'
            - '%proxy_url%'
            - '%proxy_user%'

    # Communique avec l'API Imdb
    ki_ponthub.service.imdb:
        class: KI\PonthubBundle\Service\ImdbService
        arguments:
            - '@ki_core.service.curl'
