comments:
    type:     rest
    resource: KI\CoreBundle\Controller\CommentsController

default:
    type:     rest
    resource: KI\CoreBundle\Controller\DefaultController

images:
    type:     rest
    resource: KI\CoreBundle\Controller\ImagesController

likes:
    type:     rest
    resource: KI\CoreBundle\Controller\LikeableController
