security:
    firewalls:
        # Pas de firewall pour ces exceptions
        exceptionsHead:
            methods: [HEAD]
            pattern:  ^/(ping|courses)
            security: false

        exceptionsGet1:
            methods: [GET]
            pattern: ^/$
            security: false

        exceptionsGet2:
            methods: [GET]
            pattern: ^/(_(profiler|wdt|doc))/
            security: false

        exceptionsGet3:
            methods: [GET]
            pattern: ^/(coffee|ping|version)
            security: false

        exceptionsGet4:
            methods: [GET]
            pattern: ^/courses/.+/exercices/.+/download
            security: false

        exceptionsGet5:
            methods: [GET]
            pattern: ^/users/.+/calendar
            security: false

        exceptionsGet6:
            methods: [GET]
            pattern: ^/(clubs)(/[a-zA-Z]+)?$
            security: false

        exceptionsPost1:
            methods: [POST]
            pattern: ^/(resetting|filelist|admissibles|users)
            security: false

        exceptionsDoc:
            pattern: ^/doc
            security: false

        # Firewall principal
        api:
            pattern:   ^/.+
            switch_user: { parameter: _nsa }
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix: Bearer
                query_parameter:
                    enabled: true
                    name: bearer

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^,       roles: IS_AUTHENTICATED_FULLY }
