parameters:
    # Images
    ki_core.images.directory: %kernel.root_dir%/web/uploads/images/
    ki_core.images.maxSize: 512000 # Taille maximum des images uploadées en octets
    ki_core.maintenance_lock: %kernel.root_dir%/cache/maintenance.lock
    ki_core.base_url: https://upont.enpc.fr/api/

services:
    # Interface cURL
    ki_core.service.curl:
        class: KI\CoreBundle\Service\CurlService
        arguments:
            - %proxy_url%
            - %proxy_user%

    ki_core.service.image:
        class: KI\CoreBundle\Service\ImageService
        arguments:
            - @ki_core.service.curl
            - %ki_core.images.maxSize%
