parameters:
    ki_core.images.directory: '%kernel.root_dir%/../web/uploads/images/'
    ki_core.images.maxSize: 512000 # Taille maximum des images uploadées en octets
    ki_core.maintenance_lockfile_path: '%kernel.root_dir%/../var/cache/maintenance.lock'
    ki_core.base_url: https://upont.enpc.fr/api/

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KI\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,DataFixtures}'

    KI\CoreBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    KI\CoreBundle\Service\CurlService:
        arguments:
            - '%proxy_url%'
            - '%proxy_user%'

    KI\CoreBundle\Service\ImageService:
        arguments:
            $imagesMaxSize: '%ki_core.images.maxSize%'

    KI\CoreBundle\Service\MaintenanceService:
        arguments:
            - '%ki_core.maintenance_lockfile_path%'

    KI\CoreBundle\Transformer\StringToTagsTransformer:
        arguments:
           - '@doctrine.orm.entity_manager'
           - '@ki_core.repository.tag'

    KI\CoreBundle\Selector\ImageSelector:
        tags:
           - { name: form.type, alias: image_selector }

    KI\CoreBundle\Selector\TagsSelector:
        tags:
           - { name: form.type, alias: tags_selector }

    ki_core.repository.tag:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - KI\CoreBundle\Entity\Tag

    KI\CoreBundle\Helper\FormHelper:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@router'
        calls:
            - [setRequest, ['@request_stack']]

    KI\CoreBundle\Helper\PaginateHelper:
        public: true
        calls:
            - [setRequest, ['@request_stack']]

    KI\CoreBundle\Listener\LikeableListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    KI\CoreBundle\Listener\MaintenanceListener:
        arguments:
            - '%ki_core.maintenance_lockfile_path%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    KI\CoreBundle\Listener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
