services:
    ki_core.listener.maintenance:
        class: KI\UpontBundle\EventListener\MaintenanceListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    ki_upont.images:
        class: KI\UpontBundle\Services\KIImages
        calls:
            - [ setContainer,[ @service_container ] ]



    ki_upont.type.imageuploader_selector:
       class: KI\UpontBundle\Form\Type\ImageUploaderSelectorType
       arguments: ["@doctrine.orm.entity_manager","@ki_upont.images"]
       tags:
           - { name: form.type, alias: imageuploader_selector }
    ki_upont.type.tags_selector:
       class: KI\UpontBundle\Form\Type\TagsSelectorType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
           - { name: form.type, alias: tags_selector }

    # Interface cURL
    ki_upont.curl:
        class: KI\UpontBundle\Services\KICurl
        calls:
            - [ setContainer,[ @service_container ] ]
