---
server:
    install: '1'
    packages: [vim, git, htop]
    timezone: Europe/Paris
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: 'upont.dev', ip: 192.168.34.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www/upont
    servername: 'upont.dev'
mysql:
    install: '1'
    root_password: root
    database: upont
    user: upont
    password: pass
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-gd]
composer:
    install: '1'
