imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

#nelmio_api_doc:
#    cache:
#        enabled: true

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 0
        console:
            type:  console

swiftmailer:
    spool:
        type: file
        path: '%kernel.root_dir%/spool'

sentry:
    dsn: "%sentry_dsn%"
    environment: "%kernel.environment%"
    options:
        http_proxy: "%proxy_url%"
