imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

liip_functional_test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    logging: true

twig:
    strict_variables: true

doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   pdo_mysql
                host:    '%database_host%'
                port:    '%database_port%'
                dbname:  '%database_name%'
                user:    '%database_user%'
                password: '%database_password%'
                charset:  UTF8
