imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @KICoreBundle/Resources/config/config.yml }
    - { resource: @KIFoyerBundle/Resources/config/config.yml }
    - { resource: @KIPonthubBundle/Resources/config/config.yml }
    - { resource: @KIPublicationBundle/Resources/config/config.yml }
    - { resource: @KIUserBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    KICoreBundle: ~
                    KIFoyerBundle: ~
                    KIPonthubBundle: ~
                    KIPublicationBundle: ~
                    KIUserBundle: ~
                dql:
                    string_functions:
                        soundex: KI\CoreBundle\DQL\Soundex
                        matchAgainst: KI\CoreBundle\DQL\MatchAgainst
                        month: KI\CoreBundle\DQL\Month

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    auth_mode:  %mailer_auth_mode%
    port:       %mailer_port%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: %mailer_encryption%
