ki_clubinfo:
    type:     annotation
    resource: '@KIClubinfoBundle/Controller'
    defaults: { _format: 'json' }
    prefix: /

ki_core:
    type:     annotation
    resource: '@KICoreBundle/Controller'
    defaults: { _format: 'json' }
    prefix:   /

ki_dvp:
    resource: '@KIDvpBundle/Resources/config/routing.yml'
    prefix:   /

ki_foyer:
    resource: '@KIFoyerBundle/Resources/config/routing.yml'
    prefix:   /

ki_ponthub:
    resource: '@KIPonthubBundle/Resources/config/routing.yml'
    prefix:   /

ki_publication:
    resource: '@KIPublicationBundle/Resources/config/routing.yml'
    prefix:   /

ki_user:
    resource: '@KIUserBundle/Resources/config/routing.yml'
    prefix:   /

NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /doc

login_sso:
    path: /login/sso
