ki_clubinfo:
    type:     annotation
    resource: '@KIClubinfoBundle/Controller'
    defaults: { _format: 'json' }
    prefix: /

ki_core:
    type:     annotation
    resource: '@KICoreBundle/Controller'
    defaults: { _format: 'json' }
    prefix:   /

ki_foyer:
    type:     annotation
    resource: '@KIFoyerBundle/Controller'
    defaults: { _format: 'json' }
    prefix:   /

ki_ponthub:
    type:     annotation
    resource: '@KIPonthubBundle/Controller'
    defaults: { _format: 'json' }
    prefix:   /

ki_publication:
    type:     annotation
    resource: '@KIPublicationBundle/Controller'
    defaults: { _format: 'json' }
    prefix: /

ki_user:
    type:     annotation
    resource: '@KIUserBundle/Controller'
    defaults: { _format: 'json' }
    prefix:   /

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /doc

login_sso:
    path: /login/sso
