parameters:
  upont:
    foyer:
      trust:
        - '018'
        - '019'

    promos:
      latest: '019'
      assos: '019'
      all:
        - '014'
        - '015'
        - '016'
        - '017'
        - '018'
        - '019'

    pontlyvalent:
      open: false
