parameters:
  upont:
    foyer:
      trust:
        - '020'
        - '021'

    promos:
      latest: '021'
      assos: '020'
      all:
        - '014'
        - '015'
        - '016'
        - '017'
        - '018'
        - '019'
        - '020'
        - '021'

    pontlyvalent:
      open: false
