<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150725134406 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE Likeable (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_A86380D989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_likes (post_id INT NOT NULL, liker_id INT NOT NULL, INDEX IDX_DED1C2924B89032C (post_id), INDEX IDX_DED1C292979F103A (liker_id), PRIMARY KEY(post_id, liker_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_dislikes (post_id INT NOT NULL, disliker_id INT NOT NULL, INDEX IDX_921E37B04B89032C (post_id), INDEX IDX_921E37B09DEB4BAF (disliker_id), PRIMARY KEY(post_id, disliker_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE likeable_comment (likeable_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_75D3D9ECFB414350 (likeable_id), INDEX IDX_75D3D9ECF8697D13 (comment_id), PRIMARY KEY(likeable_id, comment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Club (id INT NOT NULL, image_id INT DEFAULT NULL, banner_id INT DEFAULT NULL, fullName VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, presentation LONGTEXT DEFAULT NULL, active TINYINT(1) DEFAULT NULL, assos TINYINT(1) DEFAULT NULL, administration TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_18DC974C3DA5256D (image_id), UNIQUE INDEX UNIQ_18DC974C684EC833 (banner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', slug VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4B019DDB5E237E06 (name), UNIQUE INDEX UNIQ_4B019DDB989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, promo VARCHAR(255) DEFAULT NULL, department VARCHAR(255) DEFAULT NULL, origin VARCHAR(255) DEFAULT NULL, nationality VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, skype VARCHAR(255) DEFAULT NULL, allowedBde TINYINT(1) DEFAULT NULL, allowedBds TINYINT(1) DEFAULT NULL, statsFoyer TINYINT(1) DEFAULT NULL, statsPonthub TINYINT(1) DEFAULT NULL, details LONGTEXT DEFAULT NULL, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, nickname VARCHAR(255) DEFAULT NULL, lastConnect INT DEFAULT NULL, preferences LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', token VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_957A64793DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_B3C77447A76ED395 (user_id), INDEX IDX_B3C77447FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_club (user_id INT NOT NULL, club_id INT NOT NULL, INDEX IDX_C26F74BBA76ED395 (user_id), INDEX IDX_C26F74BB61190A32 (club_id), PRIMARY KEY(user_id, club_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CourseUser (id INT AUTO_INCREMENT NOT NULL, course_id INT NOT NULL, user_id INT NOT NULL, course_group VARCHAR(255) DEFAULT NULL, INDEX IDX_5A1BE56F591CC992 (course_id), INDEX IDX_5A1BE56FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Device (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, device VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E83B3B892FB68E (device), INDEX IDX_E83B3B87E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Achievement (id INT AUTO_INCREMENT NOT NULL, achievement INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Facegame (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, date INT NOT NULL, duration INT DEFAULT NULL, listUsers LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', promo VARCHAR(255) DEFAULT NULL, mode VARCHAR(255) DEFAULT NULL, INDEX IDX_7ACC380BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Experience (id INT NOT NULL, user_id INT DEFAULT NULL, startDate INT DEFAULT NULL, endDate INT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, description LONGTEXT DEFAULT NULL, category VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT NULL, INDEX IDX_4ACDC2D3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE AchievementUser (id INT AUTO_INCREMENT NOT NULL, achievement_id INT NOT NULL, user_id INT NOT NULL, date INT NOT NULL, seen TINYINT(1) DEFAULT NULL, INDEX IDX_D96D0502B3EC99FE (achievement_id), INDEX IDX_D96D0502A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Admissible (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, date VARCHAR(255) NOT NULL, scei VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, room VARCHAR(255) DEFAULT NULL, serie INT NOT NULL, details LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_C949BD7989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ClubUser (id INT AUTO_INCREMENT NOT NULL, club_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(255) NOT NULL, INDEX IDX_3ADE22C261190A32 (club_id), INDEX IDX_3ADE22C2A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Notification (id INT AUTO_INCREMENT NOT NULL, date INT NOT NULL, reason VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, resource VARCHAR(255) NOT NULL, mode VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications_recipient (notifications_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_526CE266D4BE081 (notifications_id), INDEX IDX_526CE266A76ED395 (user_id), PRIMARY KEY(notifications_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications_read (notification_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_73A811C8EF1A9D84 (notification_id), INDEX IDX_73A811C8A76ED395 (user_id), PRIMARY KEY(notification_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Comment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, date INT NOT NULL, text LONGTEXT NOT NULL, INDEX IDX_5BC96BF0F675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_likes (comment_id INT NOT NULL, liker_id INT NOT NULL, INDEX IDX_E050D68CF8697D13 (comment_id), INDEX IDX_E050D68C979F103A (liker_id), PRIMARY KEY(comment_id, liker_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_dislikes (comment_id INT NOT NULL, disliker_id INT NOT NULL, INDEX IDX_30B7DD17F8697D13 (comment_id), INDEX IDX_30B7DD179DEB4BAF (disliker_id), PRIMARY KEY(comment_id, disliker_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_3BC4F1635E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Youtube (id INT NOT NULL, user_id INT DEFAULT NULL, link VARCHAR(255) NOT NULL, date INT NOT NULL, INDEX IDX_3FC5A0A8A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Tuto (id INT NOT NULL, text LONGTEXT NOT NULL, date INT NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Post (id INT NOT NULL, image_id INT DEFAULT NULL, date INT NOT NULL, text LONGTEXT NOT NULL, authorClub_id INT DEFAULT NULL, authorUser_id INT DEFAULT NULL, INDEX IDX_FAB8C3B3B254E200 (authorClub_id), INDEX IDX_FAB8C3B374233BA7 (authorUser_id), UNIQUE INDEX UNIQ_FAB8C3B33DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Event (id INT NOT NULL, startDate INT NOT NULL, endDate INT NOT NULL, entryMethod VARCHAR(255) NOT NULL, shotgunDate INT DEFAULT NULL, shotgunLimit INT DEFAULT NULL, shotgunText LONGTEXT DEFAULT NULL, place VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_attendee (event_id INT NOT NULL, attendee_id INT NOT NULL, INDEX IDX_57BC3CB771F7E88B (event_id), INDEX IDX_57BC3CB7BCFD782A (attendee_id), PRIMARY KEY(event_id, attendee_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_pookie (event_id INT NOT NULL, pooky_id INT NOT NULL, INDEX IDX_3D3BBD0171F7E88B (event_id), INDEX IDX_3D3BBD012CFB7A12 (pooky_id), PRIMARY KEY(event_id, pooky_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE EventUser (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, user_id INT NOT NULL, shotgunDate INT NOT NULL, motivation LONGTEXT DEFAULT NULL, INDEX IDX_F3F427FD71F7E88B (event_id), INDEX IDX_F3F427FDA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CourseItem (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, location VARCHAR(255) NOT NULL, startDate INT DEFAULT NULL, endDate INT DEFAULT NULL, course_group VARCHAR(255) DEFAULT NULL, INDEX IDX_C8931638591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Fix (id INT NOT NULL, user_id INT DEFAULT NULL, problem LONGTEXT NOT NULL, date INT DEFAULT NULL, solved INT DEFAULT NULL, status VARCHAR(255) NOT NULL, fix TINYINT(1) NOT NULL, INDEX IDX_61B70180A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fix_respos (fix_id INT NOT NULL, respo_id INT NOT NULL, INDEX IDX_74B15CFECCC6CC89 (fix_id), INDEX IDX_74B15CFEDCF84E11 (respo_id), PRIMARY KEY(fix_id, respo_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Course (id INT NOT NULL, semester VARCHAR(255) DEFAULT NULL, department VARCHAR(255) NOT NULL, ects DOUBLE PRECISION DEFAULT NULL, active TINYINT(1) DEFAULT NULL, course_groups LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Newsitem (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Exercice (id INT NOT NULL, uploader_id INT NOT NULL, course_id INT NOT NULL, date INT NOT NULL, valid TINYINT(1) DEFAULT NULL, INDEX IDX_1D6EA51B16678C77 (uploader_id), INDEX IDX_1D6EA51B591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PonthubFile (id INT NOT NULL, image_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, size BIGINT DEFAULT NULL, added INT DEFAULT NULL, status VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_82C30A863DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ponthubfile_tag (ponthubfile_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_1995F80179A29844 (ponthubfile_id), INDEX IDX_1995F801BAD26311 (tag_id), PRIMARY KEY(ponthubfile_id, tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ponthubfile_genre (ponthubfile_id INT NOT NULL, genre_id INT NOT NULL, INDEX IDX_6C868F2C79A29844 (ponthubfile_id), INDEX IDX_6C868F2C4296D31F (genre_id), PRIMARY KEY(ponthubfile_id, genre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Serie (id INT NOT NULL, duration INT DEFAULT NULL, year INT DEFAULT NULL, vo TINYINT(1) DEFAULT NULL, vf TINYINT(1) DEFAULT NULL, vost TINYINT(1) DEFAULT NULL, vostfr TINYINT(1) DEFAULT NULL, hd TINYINT(1) DEFAULT NULL, director VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serie_actor (serie_id INT NOT NULL, actor_id INT NOT NULL, INDEX IDX_8C79626DD94388BD (serie_id), INDEX IDX_8C79626D10DAF24A (actor_id), PRIMARY KEY(serie_id, actor_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Request (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, date INT DEFAULT NULL, votes INT DEFAULT NULL, UNIQUE INDEX UNIQ_F42AB603989D9B62 (slug), INDEX IDX_F42AB603A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Music (id INT NOT NULL, album_id INT DEFAULT NULL, INDEX IDX_C930D4E1137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Episode (id INT NOT NULL, serie_id INT DEFAULT NULL, season INT NOT NULL, number INT NOT NULL, INDEX IDX_12172546D94388BD (serie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Software (id INT NOT NULL, year INT DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Album (id INT NOT NULL, artist VARCHAR(255) NOT NULL, year INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PonthubFileUser (id INT AUTO_INCREMENT NOT NULL, file_id INT NOT NULL, user_id INT NOT NULL, date INT NOT NULL, INDEX IDX_B6573C793CB796C (file_id), INDEX IDX_B6573C7A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Movie (id INT NOT NULL, duration INT DEFAULT NULL, year INT DEFAULT NULL, vo TINYINT(1) DEFAULT NULL, vf TINYINT(1) DEFAULT NULL, vost TINYINT(1) DEFAULT NULL, vostfr TINYINT(1) DEFAULT NULL, hd TINYINT(1) DEFAULT NULL, director VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movie_actor (movie_id INT NOT NULL, actor_id INT NOT NULL, INDEX IDX_3A374C658F93B6FC (movie_id), INDEX IDX_3A374C6510DAF24A (actor_id), PRIMARY KEY(movie_id, actor_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Actor (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_85B479FD5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Game (id INT NOT NULL, year INT DEFAULT NULL, studio VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Genre (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_42911CFC5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Other (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Image (id INT AUTO_INCREMENT NOT NULL, ext VARCHAR(255) NOT NULL, alt VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE post_likes ADD CONSTRAINT FK_DED1C2924B89032C FOREIGN KEY (post_id) REFERENCES Likeable (id)');
        $this->addSql('ALTER TABLE post_likes ADD CONSTRAINT FK_DED1C292979F103A FOREIGN KEY (liker_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE post_dislikes ADD CONSTRAINT FK_921E37B04B89032C FOREIGN KEY (post_id) REFERENCES Likeable (id)');
        $this->addSql('ALTER TABLE post_dislikes ADD CONSTRAINT FK_921E37B09DEB4BAF FOREIGN KEY (disliker_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE likeable_comment ADD CONSTRAINT FK_75D3D9ECFB414350 FOREIGN KEY (likeable_id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE likeable_comment ADD CONSTRAINT FK_75D3D9ECF8697D13 FOREIGN KEY (comment_id) REFERENCES Comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Club ADD CONSTRAINT FK_18DC974C3DA5256D FOREIGN KEY (image_id) REFERENCES Image (id)');
        $this->addSql('ALTER TABLE Club ADD CONSTRAINT FK_18DC974C684EC833 FOREIGN KEY (banner_id) REFERENCES Image (id)');
        $this->addSql('ALTER TABLE Club ADD CONSTRAINT FK_18DC974CBF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A64793DA5256D FOREIGN KEY (image_id) REFERENCES Image (id)');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_group (id)');
        $this->addSql('ALTER TABLE user_club ADD CONSTRAINT FK_C26F74BBA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_club ADD CONSTRAINT FK_C26F74BB61190A32 FOREIGN KEY (club_id) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE CourseUser ADD CONSTRAINT FK_5A1BE56F591CC992 FOREIGN KEY (course_id) REFERENCES Course (id)');
        $this->addSql('ALTER TABLE CourseUser ADD CONSTRAINT FK_5A1BE56FA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Device ADD CONSTRAINT FK_E83B3B87E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Facegame ADD CONSTRAINT FK_7ACC380BA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Experience ADD CONSTRAINT FK_4ACDC2D3A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Experience ADD CONSTRAINT FK_4ACDC2D3BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE AchievementUser ADD CONSTRAINT FK_D96D0502B3EC99FE FOREIGN KEY (achievement_id) REFERENCES Achievement (id)');
        $this->addSql('ALTER TABLE AchievementUser ADD CONSTRAINT FK_D96D0502A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE ClubUser ADD CONSTRAINT FK_3ADE22C261190A32 FOREIGN KEY (club_id) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE ClubUser ADD CONSTRAINT FK_3ADE22C2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE notifications_recipient ADD CONSTRAINT FK_526CE266D4BE081 FOREIGN KEY (notifications_id) REFERENCES Notification (id)');
        $this->addSql('ALTER TABLE notifications_recipient ADD CONSTRAINT FK_526CE266A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE notifications_read ADD CONSTRAINT FK_73A811C8EF1A9D84 FOREIGN KEY (notification_id) REFERENCES Notification (id)');
        $this->addSql('ALTER TABLE notifications_read ADD CONSTRAINT FK_73A811C8A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Comment ADD CONSTRAINT FK_5BC96BF0F675F31B FOREIGN KEY (author_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE comment_likes ADD CONSTRAINT FK_E050D68CF8697D13 FOREIGN KEY (comment_id) REFERENCES Comment (id)');
        $this->addSql('ALTER TABLE comment_likes ADD CONSTRAINT FK_E050D68C979F103A FOREIGN KEY (liker_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE comment_dislikes ADD CONSTRAINT FK_30B7DD17F8697D13 FOREIGN KEY (comment_id) REFERENCES Comment (id)');
        $this->addSql('ALTER TABLE comment_dislikes ADD CONSTRAINT FK_30B7DD179DEB4BAF FOREIGN KEY (disliker_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Youtube ADD CONSTRAINT FK_3FC5A0A8A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Youtube ADD CONSTRAINT FK_3FC5A0A8BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Tuto ADD CONSTRAINT FK_A14F2D69BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Post ADD CONSTRAINT FK_FAB8C3B3B254E200 FOREIGN KEY (authorClub_id) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Post ADD CONSTRAINT FK_FAB8C3B374233BA7 FOREIGN KEY (authorUser_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Post ADD CONSTRAINT FK_FAB8C3B33DA5256D FOREIGN KEY (image_id) REFERENCES Image (id)');
        $this->addSql('ALTER TABLE Post ADD CONSTRAINT FK_FAB8C3B3BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Event ADD CONSTRAINT FK_FA6F25A3BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_attendee ADD CONSTRAINT FK_57BC3CB771F7E88B FOREIGN KEY (event_id) REFERENCES Event (id)');
        $this->addSql('ALTER TABLE event_attendee ADD CONSTRAINT FK_57BC3CB7BCFD782A FOREIGN KEY (attendee_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE event_pookie ADD CONSTRAINT FK_3D3BBD0171F7E88B FOREIGN KEY (event_id) REFERENCES Event (id)');
        $this->addSql('ALTER TABLE event_pookie ADD CONSTRAINT FK_3D3BBD012CFB7A12 FOREIGN KEY (pooky_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE EventUser ADD CONSTRAINT FK_F3F427FD71F7E88B FOREIGN KEY (event_id) REFERENCES Event (id)');
        $this->addSql('ALTER TABLE EventUser ADD CONSTRAINT FK_F3F427FDA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE CourseItem ADD CONSTRAINT FK_C8931638591CC992 FOREIGN KEY (course_id) REFERENCES Course (id)');
        $this->addSql('ALTER TABLE Fix ADD CONSTRAINT FK_61B70180A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Fix ADD CONSTRAINT FK_61B70180BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fix_respos ADD CONSTRAINT FK_74B15CFECCC6CC89 FOREIGN KEY (fix_id) REFERENCES Fix (id)');
        $this->addSql('ALTER TABLE fix_respos ADD CONSTRAINT FK_74B15CFEDCF84E11 FOREIGN KEY (respo_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Course ADD CONSTRAINT FK_11326A8FBF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Newsitem ADD CONSTRAINT FK_16B13190BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Exercice ADD CONSTRAINT FK_1D6EA51B16678C77 FOREIGN KEY (uploader_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Exercice ADD CONSTRAINT FK_1D6EA51B591CC992 FOREIGN KEY (course_id) REFERENCES Course (id)');
        $this->addSql('ALTER TABLE Exercice ADD CONSTRAINT FK_1D6EA51BBF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PonthubFile ADD CONSTRAINT FK_82C30A863DA5256D FOREIGN KEY (image_id) REFERENCES Image (id)');
        $this->addSql('ALTER TABLE PonthubFile ADD CONSTRAINT FK_82C30A86BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ponthubfile_tag ADD CONSTRAINT FK_1995F80179A29844 FOREIGN KEY (ponthubfile_id) REFERENCES PonthubFile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ponthubfile_tag ADD CONSTRAINT FK_1995F801BAD26311 FOREIGN KEY (tag_id) REFERENCES Tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ponthubfile_genre ADD CONSTRAINT FK_6C868F2C79A29844 FOREIGN KEY (ponthubfile_id) REFERENCES PonthubFile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ponthubfile_genre ADD CONSTRAINT FK_6C868F2C4296D31F FOREIGN KEY (genre_id) REFERENCES Genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Serie ADD CONSTRAINT FK_6BFBBC30BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serie_actor ADD CONSTRAINT FK_8C79626DD94388BD FOREIGN KEY (serie_id) REFERENCES Serie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serie_actor ADD CONSTRAINT FK_8C79626D10DAF24A FOREIGN KEY (actor_id) REFERENCES Actor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Request ADD CONSTRAINT FK_F42AB603A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Music ADD CONSTRAINT FK_C930D4E1137ABCF FOREIGN KEY (album_id) REFERENCES Album (id)');
        $this->addSql('ALTER TABLE Music ADD CONSTRAINT FK_C930D4EBF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Episode ADD CONSTRAINT FK_12172546D94388BD FOREIGN KEY (serie_id) REFERENCES Serie (id)');
        $this->addSql('ALTER TABLE Episode ADD CONSTRAINT FK_12172546BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Software ADD CONSTRAINT FK_8EA60A99BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Album ADD CONSTRAINT FK_F8594147BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE PonthubFileUser ADD CONSTRAINT FK_B6573C793CB796C FOREIGN KEY (file_id) REFERENCES PonthubFile (id)');
        $this->addSql('ALTER TABLE PonthubFileUser ADD CONSTRAINT FK_B6573C7A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE Movie ADD CONSTRAINT FK_DC9FDD6BBF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_actor ADD CONSTRAINT FK_3A374C658F93B6FC FOREIGN KEY (movie_id) REFERENCES Movie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_actor ADD CONSTRAINT FK_3A374C6510DAF24A FOREIGN KEY (actor_id) REFERENCES Actor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Game ADD CONSTRAINT FK_83199EB2BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Other ADD CONSTRAINT FK_18991A24BF396750 FOREIGN KEY (id) REFERENCES Likeable (id) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE post_likes DROP FOREIGN KEY FK_DED1C2924B89032C');
        $this->addSql('ALTER TABLE post_dislikes DROP FOREIGN KEY FK_921E37B04B89032C');
        $this->addSql('ALTER TABLE likeable_comment DROP FOREIGN KEY FK_75D3D9ECFB414350');
        $this->addSql('ALTER TABLE Club DROP FOREIGN KEY FK_18DC974CBF396750');
        $this->addSql('ALTER TABLE Experience DROP FOREIGN KEY FK_4ACDC2D3BF396750');
        $this->addSql('ALTER TABLE Youtube DROP FOREIGN KEY FK_3FC5A0A8BF396750');
        $this->addSql('ALTER TABLE Tuto DROP FOREIGN KEY FK_A14F2D69BF396750');
        $this->addSql('ALTER TABLE Post DROP FOREIGN KEY FK_FAB8C3B3BF396750');
        $this->addSql('ALTER TABLE Event DROP FOREIGN KEY FK_FA6F25A3BF396750');
        $this->addSql('ALTER TABLE Fix DROP FOREIGN KEY FK_61B70180BF396750');
        $this->addSql('ALTER TABLE Course DROP FOREIGN KEY FK_11326A8FBF396750');
        $this->addSql('ALTER TABLE Newsitem DROP FOREIGN KEY FK_16B13190BF396750');
        $this->addSql('ALTER TABLE Exercice DROP FOREIGN KEY FK_1D6EA51BBF396750');
        $this->addSql('ALTER TABLE PonthubFile DROP FOREIGN KEY FK_82C30A86BF396750');
        $this->addSql('ALTER TABLE Serie DROP FOREIGN KEY FK_6BFBBC30BF396750');
        $this->addSql('ALTER TABLE Music DROP FOREIGN KEY FK_C930D4EBF396750');
        $this->addSql('ALTER TABLE Episode DROP FOREIGN KEY FK_12172546BF396750');
        $this->addSql('ALTER TABLE Software DROP FOREIGN KEY FK_8EA60A99BF396750');
        $this->addSql('ALTER TABLE Album DROP FOREIGN KEY FK_F8594147BF396750');
        $this->addSql('ALTER TABLE Movie DROP FOREIGN KEY FK_DC9FDD6BBF396750');
        $this->addSql('ALTER TABLE Game DROP FOREIGN KEY FK_83199EB2BF396750');
        $this->addSql('ALTER TABLE Other DROP FOREIGN KEY FK_18991A24BF396750');
        $this->addSql('ALTER TABLE user_club DROP FOREIGN KEY FK_C26F74BB61190A32');
        $this->addSql('ALTER TABLE ClubUser DROP FOREIGN KEY FK_3ADE22C261190A32');
        $this->addSql('ALTER TABLE Post DROP FOREIGN KEY FK_FAB8C3B3B254E200');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE post_likes DROP FOREIGN KEY FK_DED1C292979F103A');
        $this->addSql('ALTER TABLE post_dislikes DROP FOREIGN KEY FK_921E37B09DEB4BAF');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE user_club DROP FOREIGN KEY FK_C26F74BBA76ED395');
        $this->addSql('ALTER TABLE CourseUser DROP FOREIGN KEY FK_5A1BE56FA76ED395');
        $this->addSql('ALTER TABLE Device DROP FOREIGN KEY FK_E83B3B87E3C61F9');
        $this->addSql('ALTER TABLE Facegame DROP FOREIGN KEY FK_7ACC380BA76ED395');
        $this->addSql('ALTER TABLE Experience DROP FOREIGN KEY FK_4ACDC2D3A76ED395');
        $this->addSql('ALTER TABLE AchievementUser DROP FOREIGN KEY FK_D96D0502A76ED395');
        $this->addSql('ALTER TABLE ClubUser DROP FOREIGN KEY FK_3ADE22C2A76ED395');
        $this->addSql('ALTER TABLE notifications_recipient DROP FOREIGN KEY FK_526CE266A76ED395');
        $this->addSql('ALTER TABLE notifications_read DROP FOREIGN KEY FK_73A811C8A76ED395');
        $this->addSql('ALTER TABLE Comment DROP FOREIGN KEY FK_5BC96BF0F675F31B');
        $this->addSql('ALTER TABLE comment_likes DROP FOREIGN KEY FK_E050D68C979F103A');
        $this->addSql('ALTER TABLE comment_dislikes DROP FOREIGN KEY FK_30B7DD179DEB4BAF');
        $this->addSql('ALTER TABLE Youtube DROP FOREIGN KEY FK_3FC5A0A8A76ED395');
        $this->addSql('ALTER TABLE Post DROP FOREIGN KEY FK_FAB8C3B374233BA7');
        $this->addSql('ALTER TABLE event_attendee DROP FOREIGN KEY FK_57BC3CB7BCFD782A');
        $this->addSql('ALTER TABLE event_pookie DROP FOREIGN KEY FK_3D3BBD012CFB7A12');
        $this->addSql('ALTER TABLE EventUser DROP FOREIGN KEY FK_F3F427FDA76ED395');
        $this->addSql('ALTER TABLE Fix DROP FOREIGN KEY FK_61B70180A76ED395');
        $this->addSql('ALTER TABLE fix_respos DROP FOREIGN KEY FK_74B15CFEDCF84E11');
        $this->addSql('ALTER TABLE Exercice DROP FOREIGN KEY FK_1D6EA51B16678C77');
        $this->addSql('ALTER TABLE Request DROP FOREIGN KEY FK_F42AB603A76ED395');
        $this->addSql('ALTER TABLE PonthubFileUser DROP FOREIGN KEY FK_B6573C7A76ED395');
        $this->addSql('ALTER TABLE AchievementUser DROP FOREIGN KEY FK_D96D0502B3EC99FE');
        $this->addSql('ALTER TABLE notifications_recipient DROP FOREIGN KEY FK_526CE266D4BE081');
        $this->addSql('ALTER TABLE notifications_read DROP FOREIGN KEY FK_73A811C8EF1A9D84');
        $this->addSql('ALTER TABLE likeable_comment DROP FOREIGN KEY FK_75D3D9ECF8697D13');
        $this->addSql('ALTER TABLE comment_likes DROP FOREIGN KEY FK_E050D68CF8697D13');
        $this->addSql('ALTER TABLE comment_dislikes DROP FOREIGN KEY FK_30B7DD17F8697D13');
        $this->addSql('ALTER TABLE ponthubfile_tag DROP FOREIGN KEY FK_1995F801BAD26311');
        $this->addSql('ALTER TABLE event_attendee DROP FOREIGN KEY FK_57BC3CB771F7E88B');
        $this->addSql('ALTER TABLE event_pookie DROP FOREIGN KEY FK_3D3BBD0171F7E88B');
        $this->addSql('ALTER TABLE EventUser DROP FOREIGN KEY FK_F3F427FD71F7E88B');
        $this->addSql('ALTER TABLE fix_respos DROP FOREIGN KEY FK_74B15CFECCC6CC89');
        $this->addSql('ALTER TABLE CourseUser DROP FOREIGN KEY FK_5A1BE56F591CC992');
        $this->addSql('ALTER TABLE CourseItem DROP FOREIGN KEY FK_C8931638591CC992');
        $this->addSql('ALTER TABLE Exercice DROP FOREIGN KEY FK_1D6EA51B591CC992');
        $this->addSql('ALTER TABLE ponthubfile_tag DROP FOREIGN KEY FK_1995F80179A29844');
        $this->addSql('ALTER TABLE ponthubfile_genre DROP FOREIGN KEY FK_6C868F2C79A29844');
        $this->addSql('ALTER TABLE PonthubFileUser DROP FOREIGN KEY FK_B6573C793CB796C');
        $this->addSql('ALTER TABLE serie_actor DROP FOREIGN KEY FK_8C79626DD94388BD');
        $this->addSql('ALTER TABLE Episode DROP FOREIGN KEY FK_12172546D94388BD');
        $this->addSql('ALTER TABLE Music DROP FOREIGN KEY FK_C930D4E1137ABCF');
        $this->addSql('ALTER TABLE movie_actor DROP FOREIGN KEY FK_3A374C658F93B6FC');
        $this->addSql('ALTER TABLE serie_actor DROP FOREIGN KEY FK_8C79626D10DAF24A');
        $this->addSql('ALTER TABLE movie_actor DROP FOREIGN KEY FK_3A374C6510DAF24A');
        $this->addSql('ALTER TABLE ponthubfile_genre DROP FOREIGN KEY FK_6C868F2C4296D31F');
        $this->addSql('ALTER TABLE Club DROP FOREIGN KEY FK_18DC974C3DA5256D');
        $this->addSql('ALTER TABLE Club DROP FOREIGN KEY FK_18DC974C684EC833');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64793DA5256D');
        $this->addSql('ALTER TABLE Post DROP FOREIGN KEY FK_FAB8C3B33DA5256D');
        $this->addSql('ALTER TABLE PonthubFile DROP FOREIGN KEY FK_82C30A863DA5256D');
        $this->addSql('DROP TABLE Likeable');
        $this->addSql('DROP TABLE post_likes');
        $this->addSql('DROP TABLE post_dislikes');
        $this->addSql('DROP TABLE likeable_comment');
        $this->addSql('DROP TABLE Club');
        $this->addSql('DROP TABLE fos_group');
        $this->addSql('DROP TABLE fos_user');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE user_club');
        $this->addSql('DROP TABLE CourseUser');
        $this->addSql('DROP TABLE Device');
        $this->addSql('DROP TABLE Achievement');
        $this->addSql('DROP TABLE Facegame');
        $this->addSql('DROP TABLE Experience');
        $this->addSql('DROP TABLE AchievementUser');
        $this->addSql('DROP TABLE Admissible');
        $this->addSql('DROP TABLE ClubUser');
        $this->addSql('DROP TABLE Notification');
        $this->addSql('DROP TABLE notifications_recipient');
        $this->addSql('DROP TABLE notifications_read');
        $this->addSql('DROP TABLE Comment');
        $this->addSql('DROP TABLE comment_likes');
        $this->addSql('DROP TABLE comment_dislikes');
        $this->addSql('DROP TABLE Tag');
        $this->addSql('DROP TABLE Youtube');
        $this->addSql('DROP TABLE Tuto');
        $this->addSql('DROP TABLE Post');
        $this->addSql('DROP TABLE Event');
        $this->addSql('DROP TABLE event_attendee');
        $this->addSql('DROP TABLE event_pookie');
        $this->addSql('DROP TABLE EventUser');
        $this->addSql('DROP TABLE CourseItem');
        $this->addSql('DROP TABLE Fix');
        $this->addSql('DROP TABLE fix_respos');
        $this->addSql('DROP TABLE Course');
        $this->addSql('DROP TABLE Newsitem');
        $this->addSql('DROP TABLE Exercice');
        $this->addSql('DROP TABLE PonthubFile');
        $this->addSql('DROP TABLE ponthubfile_tag');
        $this->addSql('DROP TABLE ponthubfile_genre');
        $this->addSql('DROP TABLE Serie');
        $this->addSql('DROP TABLE serie_actor');
        $this->addSql('DROP TABLE Request');
        $this->addSql('DROP TABLE Music');
        $this->addSql('DROP TABLE Episode');
        $this->addSql('DROP TABLE Software');
        $this->addSql('DROP TABLE Album');
        $this->addSql('DROP TABLE PonthubFileUser');
        $this->addSql('DROP TABLE Movie');
        $this->addSql('DROP TABLE movie_actor');
        $this->addSql('DROP TABLE Actor');
        $this->addSql('DROP TABLE Game');
        $this->addSql('DROP TABLE Genre');
        $this->addSql('DROP TABLE Other');
        $this->addSql('DROP TABLE Image');
    }
}
